[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[[mouse.bindings]]
mouse = "Left"
action = "Copy"

[[mouse.bindings]]
mouse = "Right"
action = "Paste"

