[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = [
  "-l",
  "-c",
  "tmux has-session -t default 2>/dev/null && tmux attach -t default || tmux new -s default"
]

[font]
size = 14.0

[font.normal]
family = "JetBrains Mono"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Fullscreen"
