[env]
TERM = "xterm-256color"

[terminal.shell]
program = "sh"
args = [
    "-c",
    "tmux has-session -t default 2>/dev/null && tmux attach -t default || tmux new -s default"
]


[window]
decorations = "None"
startup_mode = "Fullscreen"
